
intermediate_exchange_names = [ # ecoinvent 3.4 cutoff
    'heavy water',
    'irrigation',
    'rainwater mineral oil storage',
    'tap water',
    'wastewater from anaerobic digestion of whey',
    'wastewater from black chrome coating',
    'wastewater from cathode ray tube production',
    'wastewater from ceramic production',
    'wastewater from concrete production',
    'wastewater from glass production',
    'wastewater from grass refinery',
    'wastewater from ground granulated blast furnace slag production',
    'wastewater from hard fibreboard production',
    'wastewater from liquid crystal display backlight production',
    'wastewater from liquid crystal display production',
    'wastewater from liquid crystal production',
    'wastewater from lorry production',
    'wastewater from maize starch production',
    'wastewater from medium density board production',
    'wastewater from particle board production',
    'wastewater from pig iron production',
    'wastewater from plywood production',
    'wastewater from potato starch production',
    'wastewater from PV cell production',
    'wastewater from soft fibreboard production',
    'wastewater from tube collector production',
    'wastewater from vegetable oil refinery',
    'wastewater from wafer fabrication',
    'wastewater, average',
    'wastewater, from residence',
    'wastewater, unpolluted',
    'wastewater, unpolluted, from residence',
    'water discharge from petroleum extraction, offshore',
    'water discharge from petroleum/natural gas extraction, onshore',
    'water, completely softened, from decarbonised water, at user',
    'water, decarbonised, at user',
    'water, deionised, from tap water, at user',
    'water, ultrapure'
]
